server:
  port: 8080


# SPRING PROFILES
spring:
  # HTTP ENCODING
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1dy?userUnicode=true&characterEncoding=utf-8
    username: study
    password: 123

    #Druid
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000


  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.xgblack.heatmap.entity cn.xgblack.heatmap.dto